apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knf1.fullname" . }}
  labels:
    {{- include "knf1.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "knf1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: accessnet, internalnet-1
      labels:
        {{- include "knf1.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "knf1.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: ["/bin/sleep", "3650d"]    
          command:
            - /bin/bash 
            - -exc
            - |
                /usr/share/openvswitch/scripts/ovs-ctl start
                ovs-vsctl add-br br0
                ovs-vsctl add-port br0 vxlan1 -- set interface vxlan1 type=vxlan options:remote_ip=192.168.16.2
                ip link add vxlan2 type vxlan id 0 remote 10.255.0.2 dstport 4789 dev net1
                ovs-vsctl add-port br0 vxlan2
                ifconfig vxlan2 up
                ovs-vsctl set bridge br0 protocols=OpenFlow10,OpenFlow12,OpenFlow13
                ovs-vsctl set-controller br0 tcp::127.0.0.1:6633
                ovs-vsctl set-manager ptcp:6632
                ovs-vsctl set-fail-mode br0 secure
                ovs-vsctl set bridge br0 other-config:datapath-id=0000000000000001
                ryu-manager ryu.app.rest_qos ryu.app.rest_conf_switch -/qos_simple_switch_13.py
                /bin/sleep 3650d
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
